name: buddyjet
description: Your buddy-budget tracker
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  backdrop: ^0.9.0
  cached_network_image: ^3.2.3
  camera: ^0.10.5+2
  card_swiper: ^3.0.1
  connectivity_plus: ^4.0.2
  cupertino_icons: ^1.0.5
  device_info_plus: ^9.0.3
  dots_indicator: ^3.0.0
  equatable: ^2.0.5
  fade_shimmer: ^2.2.0
  file_picker: ^5.3.3
  flutter_feather_icons: ^2.0.0+1
  flutter_slidable: ^3.0.0
  flutter_smart_dialog: ^4.9.4
  flutter_svg: ^2.0.7
  flutter_tabler_icons: ^1.2.0
  flutter_whatsnew: ^1.0.5+2
  fluttertoast: ^8.2.2
  get: ^4.6.5
  get_storage: ^2.1.1
  image_cropper: ^5.0.0
  intl: ^0.18.1
  lottie: ^2.5.0
  mask_text_input_formatter: ^2.5.0
  package_info_plus: ^4.1.0
  percent_indicator: ^4.2.3
  permission_handler: ^10.4.3
  photo_view: ^0.14.0
  screenshot: ^2.1.0
  settings_ui: ^2.0.2
  share_plus: ^7.1.0
  sticky_headers: ^0.3.0+2
  syncfusion_flutter_charts: ^22.2.7
  syncfusion_flutter_datepicker: ^22.2.7
  url_launcher: ^6.1.12

  #  Coming soon
  #  syncfusion_flutter_gauges: ^22.2.7
  #  syncfusion_flutter_datagrid: ^22.2.7
  #  syncfusion_flutter_datagrid_export: ^22.2.7
  #  syncfusion_officechart: ^22.2.7
  #  in_app_review: ^2.0.6
  #  flutter_barcode_scanner: ^2.0.0
  #  flutter_local_notifications: ^15.1.0+1
  #  showcaseview: ^2.0.3
  #  liquid_swipe: ^3.1.0
  #  confetti: ^0.7.0
  #  keyboard_actions: ^4.2.0
  #  feature_discovery: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  build_runner:
  flutter_lints: ^2.0.2
  flutter_gen_runner:
  pubspec_dependency_sorter: ^1.0.3

# Auto-sort dependencies
# flutter pub run pubspec_dependency_sorter

# Generated by FlutterGen
# Run this after editing gen config "flutter packages pub run build_runner build"
flutter_gen:
  integrations:
    flutter_svg: true

  colors:
    inputs:
      - assets/color/colors.xml

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Outfit
       fonts:
         - asset: fonts/Outfit/static/Outfit-Black.ttf
           weight: 900
         - asset: fonts/Outfit/static/Outfit-ExtraBold.ttf
           weight: 800
         - asset: fonts/Outfit/static/Outfit-Bold.ttf
           weight: 700
         - asset: fonts/Outfit/static/Outfit-SemiBold.ttf
           weight: 600
         - asset: fonts/Outfit/static/Outfit-Regular.ttf
           weight: 500
         - asset: fonts/Outfit/static/Outfit-Medium.ttf
           weight: 400
         - asset: fonts/Outfit/static/Outfit-Light.ttf
           weight: 300
         - asset: fonts/Outfit/static/Outfit-ExtraLight.ttf
           weight: 200
         - asset: fonts/Outfit/static/Outfit-Thin.ttf
           weight: 100

     - family: Cabin
       fonts:
         - asset: fonts/Cabin/static/Cabin-Bold.ttf
           weight: 700
         - asset: fonts/Cabin/static/Cabin-SemiBold.ttf
           weight: 600
         - asset: fonts/Cabin/static/Cabin-Regular.ttf
           weight: 500
         - asset: fonts/Cabin/static/Cabin-Medium.ttf
           weight: 400
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
